name: primeorder

on:
  pull_request:
    paths:
      - ".github/workflows/primeorder.yml"
      - "primeorder/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: primeorder

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
    steps:
    - uses: actions/checkout@v3
    - uses: risc0/risc0/.github/actions/rustup@main
      with:
        toolchain: ${{ matrix.rust }}
    - run: cargo check --all-features
    - run: cargo test --no-default-features
    - run: cargo test
    - run: cargo test --all-features

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: risc0/risc0/.github/actions/rustup@main
        with:
          toolchain: stable
      - run: cargo doc --all-features
